// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUDJLYRg8eMg66zgE1yt3Ls3iYQlLu7PA',
    appId: '1:850654486873:web:37e90750c56e07c481ac48',
    messagingSenderId: '850654486873',
    projectId: 'platzitripsflutter-50f5a',
    authDomain: 'platzitripsflutter-50f5a.firebaseapp.com',
    storageBucket: 'platzitripsflutter-50f5a.appspot.com',
    measurementId: 'G-DW4X039QE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiVe9Wxwa1a7jxJp5NSGoi9KWtWkWqyDQ',
    appId: '1:850654486873:android:87c7f31a16da011181ac48',
    messagingSenderId: '850654486873',
    projectId: 'platzitripsflutter-50f5a',
    storageBucket: 'platzitripsflutter-50f5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4o1s-uL7RTlZA8b9VDB0V2YV5ZgwrD_I',
    appId: '1:850654486873:ios:c07f41dbe47f671081ac48',
    messagingSenderId: '850654486873',
    projectId: 'platzitripsflutter-50f5a',
    storageBucket: 'platzitripsflutter-50f5a.appspot.com',
    iosClientId: '850654486873-ipm799c7je6b5m5tk5dlbr9qkddmc112.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4o1s-uL7RTlZA8b9VDB0V2YV5ZgwrD_I',
    appId: '1:850654486873:ios:c07f41dbe47f671081ac48',
    messagingSenderId: '850654486873',
    projectId: 'platzitripsflutter-50f5a',
    storageBucket: 'platzitripsflutter-50f5a.appspot.com',
    iosClientId: '850654486873-ipm799c7je6b5m5tk5dlbr9qkddmc112.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );
}
